name: iderma
description:   "iDerma is a revolutionary mobile application that harnesses the power of artificial intelligence (AI) and the camera on your phone to identify a wide range of human skin diseases, identify a wide range of skin diseases."
publish_to: 'none'
version: 1.1.6


# ---------------------------
# The environment section ensures compatibility with a specific Dart version.
# ---------------------------
environment:
  sdk: '>=3.3.0 <4.0.0'


# ---------------------------
# Dependencies for your project.
# ---------------------------
dependencies:
  flutter:
    sdk: flutter

  # Firebase

  # Camera

  # CupertinoIcons for iOS style icons
  cupertino_icons: ^1.0.6 


# ---------------------------
# Dev dependencies for testing and code generation.
# ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.0


# ---------------------------
# Flutter-specific configuration options
# ---------------------------
flutter:

  # Fonts declaration
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/fonts/
    - assets/images/introduction/details.png
    - assets/images/introduction/logo.png
    - assets/images/emb-sign.png

  uses-material-design: true