name: iderma
description:   "iDerma is a revolutionary mobile application that harnesses the power of artificial intelligence (AI) and the camera on your phone to identify a wide range of human skin diseases, identify a wide range of skin diseases."
publish_to: 'none'
version: 1.1.6


# ---------------------------
# The environment section ensures compatibility with a specific Dart version.
# ---------------------------
environment:
  sdk: '>=3.3.0 <4.0.0'


# ---------------------------
# Dependencies for your project.
# ---------------------------
dependencies:
  flutter:
    sdk: flutter

  # Firebase

  # Camera

  # CupertinoIcons for iOS style icons
  cupertino_icons: ^1.0.6 


# ---------------------------
# Dev dependencies for testing and code generation.
# ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.0


# ---------------------------
# Flutter-specific configuration options
# ---------------------------
flutter:

  uses-material-design: true

  assets:
    - assets/images/introduction/details.png
    - assets/images/introduction/logo.png
    - assets/images/emb-sign.png


  # Fonts declaration
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
