name: iderma
description: "iDerma is a revolutionary mobile application that harnesses the power of artificial intelligence (AI) and the camera on your phone to identify a wide range of human skin diseases, identify a wide range of skin diseases."
publish_to: 'none'
version: 1.2.1


# ---------------------------
# The environment section ensures compatibility with a specific Dart version.
# ---------------------------
environment:
  sdk: '^3.5.0'


# ---------------------------
# Dependencies for your project.
# ---------------------------
dependencies:
  flutter:
    sdk: flutter

  # Splash screen
  flutter_native_splash: ^2.4.1
  
  cloud_firestore: ^5.4.0

  # Provider for state management
  provider: ^6.0.5
  
  # Open URL
  url_launcher: ^6.0.20

  # Camera
  image_picker: ^1.1.2

  # HTTP 
  http: ^1.2.2

  # CupertinoIcons for iOS style icons
  cupertino_icons: ^1.0.6 
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.3

  # Google Sign In 
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1


# ---------------------------
# Dev dependencies for testing and code generation.
# ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.0

  # Application Icon
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: "assets/icon/icon.png"
  image_path: "assets/images/icons/android/res/mipmap-xxxhdpi/ic_launcher.png"
  adaptive_icon_background: "#2C3D8F"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icons/web/icon-512.png"
    background_color: "#2C3D8F"
    theme_color: "#2C3D8F"

  

# ---------------------------
# Flutter-specific configuration options
# ---------------------------
flutter:

  # Fonts declaration
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/fonts/
    - assets/images/introduction/details.png
    - assets/images/logos/logo.png
    - assets/images/logos/apple.png
    - assets/images/logos/google.png
    - assets/images/emb-sign.png
    - assets/images/logos/details.png
    - assets/images/main_menu_icons/home.png
    - assets/images/main_menu_icons/faq.png
    - assets/images/main_menu_icons/gear.png
    - assets/images/main_menu_icons/terms_of_use.png
    - assets/images/main_menu_icons/privacy_policy.png
    - assets/images/main_menu_icons/about.png
    - assets/images/main_menu_icons/logout.png
    - assets/images/logos/logo_copy.png
    - assets/images/logos/branding.png
    - assets/images/logos/logoo.png
    - assets/images/icons/android/play_store_512.png

  uses-material-design: true